### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__globals__'

### ISSUE THREAD

**Issue by DanCardin** [rochacbruno/flasgger#76] opened 2017-03-30 17:55 UTC
```
File "/usr/local/lib/python3.6/site-packages/flasgger/base.py", line 415, in get
    endpoint=rule.endpoint, verb=verb
File "/usr/local/lib/python3.6/site-packages/flasgger/base.py", line 67, in _parse_docstring
    obj.__globals__['__file__']
AttributeError: 'NoneType' object has no attribute '__globals__'
```
I get this when loading the swaggerui page on master without having any routes at all. Just instantiating the Swagger object with an app, `swag.init_app(app)` seems to cause it.

I won't be able to use what's currently released it seems, because I need the fix for swag_path that's not released yet

EDIT: Forgot to note that it does *not* happen in the most recent released version. and after attempting to narrow down the problem, it seems to be MethodViews that are the problem.

**Comment by rochacbruno** [comment] 2017-03-30 18:11
@DanCardin can you share your code so I can try to reproduce.

Thanks

**Comment by rochacbruno** [comment] 2017-03-30 18:12
I tried this

```python
from flask import Flask
from flasgger import Swagger


app = Flask(__name__)
Swagger(app)


@app.route('/')
def index():
    return 'Hello World'


if __name__ == '__main__':
    app.run(debug=True)
```

And cannot reproduce the error

**Comment by rochacbruno** [comment] 2017-03-30 18:40
@DanCardin I creates a test/example in https://github.com/rochacbruno/flasgger/commit/ed40572760204d670539e3e961d48866f4582bff

Can you please try again and also if possible share the exact code you used so we can add one more test.

(apps in examples/ folder are executed by travis for testing)

**Comment by DanCardin** [comment] 2017-03-30 18:44
```
from flasgger import Swagger                                                                                                                                                                   
from flask import Flask                                                                                                                                                                        
from flask.views import MethodView                                                                                                                                                             
                                                                                                                                                                                               
app = Flask(__name__)                                                                                                                                                                          
Swagger(app)                                                                                                                                                                                   
                                                                                                                                                                                               
class Meow(MethodView):                                                                                                                                                                        
    pass                                                                                                                                                                                       
                                                                                                                                                                                               
app.add_url_rule('/meow/<int:param>/', view_func=Meow.as_view('meow'), methods=['DELETE'])                                                                                                     
                                                                                                                                                                                               
if __name__ == '__main__':                                                                                                                                                                     
    app.run(debug=True)
```
or with any method other than POST or GET

**Comment by DanCardin** [comment] 2017-03-30 18:48
ah, now I see your test case. Yes, I guess I have rules registered for methods which I dont have implemented

**Comment by rochacbruno** [comment] 2017-03-30 19:03
Hi, I added your example to the test example in https://github.com/rochacbruno/flasgger/commit/55e9cef4cd4363f22f6c5d8282753f76729c2987

Also added a fix for the error. please confirm if it is fixed now.

Thank for your help

**Comment by rochacbruno** [comment] 2017-03-30 19:04
Having rules for missing methods is not good, it is error, but flasgger will not take care of them, flasgger will ignore and the error will raise when you try to request the rule.

**Comment by DanCardin** [comment] 2017-03-30 20:02
cool, that sounds fine

**Closed** 2017-03-30 20:02 UTC
