### ISSUE TITLE
Now incompatible with apispec

### ISSUE THREAD

**Issue by dbazhal** [rochacbruno/flasgger#235] opened 2018-09-06 15:40 UTC
When you do
```
from marshmallow import Schema, fields
```
it is None because
```
No module named 'apispec.ext.marshmallow.swagger'
```
Starting from apispec==0.39.0

**Comment by javabrett** [comment] 2018-09-07 07:28
Looks like duplicate of #205 which is fixed on master, pending release.

**Comment by rochacbruno** [comment] 2018-09-07 16:58
@javabrett do you think is it time to do a release? do you want me to add you as a pypi mantainer? what is your username there?

**Comment by javabrett** [comment] 2018-09-08 06:05
> do you think is it time to do a release?

I'm not aware of any release-blockers, and it would be good to get this release fixed, since we didn't previously pin `apispec`, so most users will hit this issue sooner-or-later.

Release notes need updating, I understand they are currently kept in https://github.com/rochacbruno/flasgger/blob/master/HISTORY .

> do you want me to add you as a pypi mantainer? what is your username there?

Thanks.  I must confess I had to create an account.  I am the paradoxical https://pypi.org/user/javabrett/ there also.

**Comment by javabrett** [comment] 2018-09-10 02:00
Closing this as duplicate, opened #237 for the release process.

**Closed by javabrett** 2018-09-10 02:00 UTC
Labels: bug, duplicate
